### ISSUE TITLE
代码泄露风险提示

### ISSUE THREAD

**Issue by xia0muma** [Computerscholler/gerstler#1]
你好~：
        发现有GitHub仓库“gerstler” 中有 关键词”@nsfocus.com“，地址 
https://github.com/jrester/gerstler/blob/fbd0188fe2f560317c77b105fb83de5a5979d7f1/documents/phrack/60/8.txt 
        我们无法确认是否包含公司产品或研发代码，请确认后回复，感谢~

**Comment by jrester** [comment]
It does not contain any nsfocus products.
